# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDGpio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpio',
            name='state',
            field=models.BooleanField(editable=False),
        ),
    ]
