# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDGpio', '0005_auto_20161108_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpios',
            name='pin',
            field=models.IntegerField(default=3, null=True),
        ),
    ]
