# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDGpio', '0006_auto_20161108_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpios',
            name='pin',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
