# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDGpio', '0008_auto_20161108_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpios',
            name='state',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
